// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1aX2w2BeYkilMITSglK1t0k8RrDZkBuM',
    appId: '1:785027783101:web:22950a5d4809f32e421ad4',
    messagingSenderId: '785027783101',
    projectId: 'sastrax-c59e2',
    authDomain: 'sastrax-c59e2.firebaseapp.com',
    databaseURL: 'https://sastrax-c59e2-default-rtdb.firebaseio.com',
    storageBucket: 'sastrax-c59e2.firebasestorage.app',
    measurementId: 'G-YV2GSKVX0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3G7H8h97AsBZi13ObKGlWbuas0-5BvA',
    appId: '1:785027783101:android:a6ea8589ea5b9a4f421ad4',
    messagingSenderId: '785027783101',
    projectId: 'sastrax-c59e2',
    databaseURL: 'https://sastrax-c59e2-default-rtdb.firebaseio.com',
    storageBucket: 'sastrax-c59e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5beIDDi9CuiDdTdevbJLzcEE0WzKQQf4',
    appId: '1:785027783101:ios:8da2f76d2998e5b0421ad4',
    messagingSenderId: '785027783101',
    projectId: 'sastrax-c59e2',
    databaseURL: 'https://sastrax-c59e2-default-rtdb.firebaseio.com',
    storageBucket: 'sastrax-c59e2.firebasestorage.app',
    iosBundleId: 'com.example.sastrax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5beIDDi9CuiDdTdevbJLzcEE0WzKQQf4',
    appId: '1:785027783101:ios:8da2f76d2998e5b0421ad4',
    messagingSenderId: '785027783101',
    projectId: 'sastrax-c59e2',
    databaseURL: 'https://sastrax-c59e2-default-rtdb.firebaseio.com',
    storageBucket: 'sastrax-c59e2.firebasestorage.app',
    iosBundleId: 'com.example.sastrax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1aX2w2BeYkilMITSglK1t0k8RrDZkBuM',
    appId: '1:785027783101:web:47b01bb289e839fa421ad4',
    messagingSenderId: '785027783101',
    projectId: 'sastrax-c59e2',
    authDomain: 'sastrax-c59e2.firebaseapp.com',
    databaseURL: 'https://sastrax-c59e2-default-rtdb.firebaseio.com',
    storageBucket: 'sastrax-c59e2.firebasestorage.app',
    measurementId: 'G-J6V8W75SVP',
  );
}
